version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    image: nerdyops-app:latest
    container_name: NerdyOps-App
    restart: always
    ports:
      - "80:80"
    environment:
      - DB_TYPE=mysql
      - DB_HOST=NerdyOps-MySQL
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=nerdyops
      - REDIS_URL=redis://NerdyOps-Redis:6379
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: NerdyOps-MySQL
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: nerdyops
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: NerdyOps-Redis
    restart: always

  webssh2:
    build:
      context: ..
      dockerfile: infra/Dockerfile.webssh2
    image: nerdyops-webssh2:latest
    container_name: NerdyOps-WebSSH2
    restart: always
    ports:
      - "2222:2222"

volumes:
  mysql-data:
