version: '3.8'

services:
  web:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: nerdyops-backend:latest
    container_name: NerdyOps-Backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      - DB_TYPE=mysql
      - DB_HOST=NerdyOps-MySQL
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=nerdyops
      - REDIS_URL=redis://NerdyOps-Redis:6379
    depends_on:
      - mysql
      - redis

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: nerdyops-frontend:latest
    container_name: NerdyOps-Frontend
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - web

  mysql:
    image: mysql:8.0
    container_name: NerdyOps-MySQL
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: nerdyops
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: NerdyOps-Redis
    restart: always

  scheduler:
    image: nerdyops-backend:latest
    container_name: NerdyOps-Scheduler
    restart: always
    command: ["python", "scheduler.py"]
    environment:
      - DB_TYPE=mysql
      - DB_HOST=NerdyOps-MySQL
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=nerdyops
      - REDIS_URL=redis://NerdyOps-Redis:6379
    depends_on:
      - mysql
      - redis

volumes:
  mysql-data:
