version: '3.8'

services:
  web:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: nerdyops-backend:latest 
    container_name: NerdyOps-Backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=NerdyOps-MySQL
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - mysql
      - redis

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: nerdyops-frontend:latest 
    container_name: NerdyOps-Frontend
    restart: always
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_CENTRAL_SERVER_URL=http://localhost:5001
    depends_on:
      - web

  mysql:
    image: mysql:8.0
    container_name: NerdyOps-MySQL
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    container_name: NerdyOps-Redis
    restart: always
    ports:
      - "6379:6379"

  scheduler:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: nerdyops-scheduler:latest 
    container_name: NerdyOps-Scheduler
    restart: always
    command: ["python", "scheduler.py"]
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=NerdyOps-MySQL
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - mysql
      - redis

volumes:
  mysql-data:
