apiVersion: apps/v1
kind: Deployment
metadata:
  name: nerdyops-redis
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nerdyops-redis
  template:
    metadata:
      labels:
        app: nerdyops-redis
    spec:
      containers:
      - name: redis
        image: {{ .Values.image.redis }}
        ports:
        - containerPort: 6379
