apiVersion: apps/v1
kind: Deployment
metadata:
  name: nerdyops-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nerdyops-frontend
  template:
    metadata:
      labels:
        app: nerdyops-frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.image.frontend }}
        ports:
        - containerPort: 3000
