apiVersion: apps/v1
kind: Deployment
metadata:
  name: nerdyops-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nerdyops-frontend
  template:
    metadata:
      labels:
        app: nerdyops-frontend
    spec:
      initContainers:
      - name: wait-for-backend
        image: busybox
        command: ['sh', '-c', 'until nc -z -v -w30 svc-nerdyops-backend 5001; do echo waiting for backend; sleep 5; done']
      containers:
      - name: frontend
        image: {{ .Values.image.frontend }}
        ports:
        - containerPort: 3000
