apiVersion: v1
kind: Service
metadata:
  name: svc-nerdyops-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nerdyops-app

---

apiVersion: v1
kind: Service
metadata:
  name: svc-nerdyops-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: nerdyops-mysql

---

apiVersion: v1
kind: Service
metadata:
  name: svc-nerdyops-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: nerdyops-redis
